modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL="https://github.com/JamCoreModding/quicker-connect-button/issues"

[[mods]]
modId = "quickerconnectbutton"
version = "${file.jarVersion}"
displayName = "Quicker Connect Button"
displayURL="https://github.com/JamCoreModding/quicker-connect-button"
logoFile = "icon.png"
authors = "Jamalam"
description = '''
Adds a connect button to the main menu for quickly connecting to servers
'''

[[dependencies.quickerconnectbutton]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quickerconnectbutton]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quickerconnectbutton]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"
