modLoader = "javafml"
loaderVersion = "[49,)"
license = "MIT"
issueTrackerURL="https://github.com/JamCoreModding/quicker-connect-button/issues"

[[mods]]
modId = "quickerconnectbutton"
version = "${file.jarVersion}"
displayName = "Quicker Connect Button"
displayURL="https://github.com/JamCoreModding/quicker-connect-button"
logoFile = "icon.png"
authors = "Jamalam"
description = '''
Adds a connect button to the main menu for quickly connecting to servers
'''

[[dependencies.quickerconnectbutton]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quickerconnectbutton]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quickerconnectbutton]]
modId = "architectury"
mandatory = true
versionRange = "[11.0.9,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.quickerconnectbutton]]
modId = "jamlib"
mandatory = true
versionRange = "[1.0.3+1.20.4,)"
ordering = "AFTER"
side = "BOTH"
