modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL="https://github.com/JamCoreModding/quicker-connect-button/issues"

[[mods]]
modId = "quickerconnectbutton"
version = "${file.jarVersion}"
displayName = "Quicker Connect Button"
displayURL="https://github.com/JamCoreModding/quicker-connect-button"
logoFile = "icon.png"
authors = "Jamalam"
description = '''
Adds a connect button to the main menu for quickly connecting to servers
'''

[[dependencies.quickerconnectbutton]]
modId = "neoforge"
mandatory = true
versionRange = "[20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quickerconnectbutton]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quickerconnectbutton]]
modId = "architectury"
mandatory = true
versionRange = "[10.0.17,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "quickerconnectbutton.mixins.json"
